name: CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eulemitkeule/blobby-online
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releaseCreated: ${{ steps.release.outputs.new-release-published }}
      version: ${{ steps.release.outputs.release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        uses: docker://ghcr.io/codfish/semantic-release-action:latest
        id: release
        with:
          tag_format: 'v${version}'
          branches: |
            [
              'master'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: belon/docker-build-push@v4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.IMAGE_NAME }}
          tags: latest,${{ needs.release.outputs.version }}